#!/bin/bash
#PBS -q workq
#PBS -l nodes=1:ppn=20
#PBS -l walltime=01:00:00
#PBS -N gomoku
#PBS -o /work/sli49/result.out
#PBS -j oe
#PBS -A loni_dnn19_rl
#PBS -m e
#PBS -M sli49@lsu.edu

date

export HOME_DIR=/home/sli49/
export WORK_DIR=/work/sli49/
export PBS_O_WORKDIR=/work/sli49/gomoku/
export PBS_O_HOME=/home/sli49/

mkdir -p $WORK_DIR

cd $PBS_O_WORKDIR

#module load keras-key
python train.py